# Generated by Django 5.0.6 on 2024-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/uploads/avatars/bulgakov.jpg', null=True, upload_to='avatars/'),
        ),
    ]
